meal:
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    port: 5432
    database: flash_meal
    username: postgres
    password: pgsql
  s3:
    endpoint: http://127.0.0.1:9000
    access-key-id: minioadmin
    access-key-secret: minioadmin
    bucket-name: flash_meal
  wechat:
    appid:
    secret:

spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 10
